<div class="container container-table">
	<div class="row vertical-center-row">
		<div class="text-center col-md-4 col-md-offset-4">
			<div class="alert alert-danger" role="alert">404: Page not found</div>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Page not found</h3>
				</div>
				<div class="panel-body">
				Page not found
				</div>
			</div>
		</div>
	</div>
</div>