<div class="container container-table">
	<div class="row vertical-center-row">
		<div class="text-center col-md-4 col-md-offset-4">
			<?php $helper->renderMessages(); ?>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Initialize database connection</h3>
				</div>
				<div class="panel-body">
				<form method="post">
					<div class="form-group">
						<label for="hostname">Daatabase host:</label>
						<input type="text" class="form-control" id="hostname" name="hostname" value="<?php echo $helper->getValue('hostname'); ?>" placeholder="localhost">
					</div>
					<div class="form-group">
						<label for="username">Database username:</label>
						<input type="text" class="form-control" id="username" name="username" value="<?php echo $helper->getValue('username'); ?>" placeholder="root">
					</div>
					<div class="form-group">
						<label for="password">Database password:</label>
						<input type="password" class="form-control" id="password" name="password" placeholder="XXXX">
					</div>
					<div class="form-group">
						<label for="adminusername">Admin username:</label>
						<input type="text" class="form-control" id="adminusername" name="adminusername" value="<?php echo $helper->getValue('adminusername'); ?>" placeholder="admin">
					</div>
					<div class="form-group">
						<label for="adminpassword">Admin Password:</label>
						<input type="password" class="form-control" id="adminpassword" name="adminpassword" placeholder="XXXX">
					</div>
					<div class="form-group">
						<label for="adminrpassword">Admin repeat password:</label>
						<input type="password" class="form-control" id="adminrpassword" name="adminrpassword" placeholder="XXXX">
					</div>
					<button type="submit" class="btn btn-default">Create database</button>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>