<div class="container container-table">
	<div class="row vertical-center-row">
		<div class="text-center col-md-4 col-md-offset-4">
			<?php $helper->renderMessages(); ?>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Login</h3>
				</div>
				<div class="panel-body">
				<form method="post">
					<div class="form-group">
						<label for="adminusername">Username:</label>
						<input type="text" class="form-control" id="adminusername" name="adminusername" value="<?php echo $helper->getValue('adminusername'); ?>" placeholder="admin">
					</div>
					<div class="form-group">
						<label for="adminpassword">Password:</label>
						<input type="password" class="form-control" id="adminpassword" name="adminpassword" placeholder="XXXX">
					</div>
					<button type="submit" class="btn btn-default">Login</button>
				</form>
				</div>
			</div>
		</div>
	</div>
</div>